name: Generate sitemap

permissions:
  contents: write  # This lets the workflow push changes
  
on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  sitemap_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://alderholt.github.io/alderholtarchives/

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit sitemap if changed
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add sitemap.xml
          git commit -m "Update sitemap.xml (auto)"
          git push
        else
          echo "No changes to commit"
        fi
